config/routes.rb
Rails.application.routes.draw do
  root 'home_page#landing_page'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  post 'room/search_room'
  post 'room/room_slots'
  post 'room/make_booking'
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booked_slot.rb
class BookedSlot < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true, format: { with: /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\z/ }
    belongs_to :slot
end

app/models/room.rb
class Room < ApplicationRecord
    attr_accessor :select_a_date, :day, :date

    has_many :slots
end

app/models/slot.rb
class Slot < ApplicationRecord
  attr_accessor :slot_id, :name, :email

  belongs_to :room
  has_one :booked_slot , dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def landing_page
    @room = Room.new
  end
end

app/controllers/room_controller.rb
class RoomController < ApplicationController
    def search_room
        @room = Room.new
        @date = params[:room][:select_a_date] if params[:room][:select_a_date].present?
        if @date.present?
          @day_on_that_date = Date.parse(@date).strftime("%A")
        else
          @day_on_that_date = nil
        end
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: turbo_stream.update("show_rooms", partial: "room/show_all_rooms",
            locals: {day: @day_on_that_date, date: @date, room: @room})
          end
        end

    end #search_room


    def room_slots
      @room = Room.find(params[:room_id])
      @slots = @room.slots
      @day = params[:room][:day]
      @date = params[:room][:date]
      @slot = Slot.new
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.append("show_room_slots", partial: "room/show_room_slots",
          locals: {day: @day, date: @date, room: @room, slots: @slots, slot: @slot, val: 0})
        end
      end
    end #room_slots

    def make_booking
     if find_already_booked? #it should be true on not finding any relative booking
      make_new_booking #make new booking
      if @slot_booked.valid?
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: turbo_stream.update("booking_message", "Booking Saved Successfully!")
          end
        end
      else
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: turbo_stream.update("booking_message", "#{@slot_booked.errors.full_messages.first}")
          end
      end
      end
    else
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.update("booking_message", "Already Booked Choose other")
        end
      end
    end
    end #make_booking

    private
    def find_already_booked?
      slot = params[:slot] if params[:slot]
      found =  Slot.joins(:booked_slot)
                   .where(booked_slots: {slot_id: slot[:slot_id], on_date: slot[:date], room_id: slot[:room]})
                   .pluck("booked_slots.id")
      found.empty? ? true : false
    end #find_already_booked

    def make_new_booking
      slot = params[:slot] if params[:slot]
      @slot_booked = BookedSlot.create(slot_id: slot[:slot_id],
                                        room_id: slot[:room],
                                        name: slot[:name],
                                        email: slot[:email],
                                        on_day: slot[:day],
                                        on_date: slot[:date])
        @slot_booked ? true : false
    end #make_new_booking
      
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/room_helper.rb
module RoomHelper
    def room_names
       Room.all.count > 0 ?  @room = Room.all.map { |room| [room.name, room.id] } : @room = []
    end

    def booked_by_user(slot, date, room)
        if_found = Slot.joins(:booked_slot)
                   .where(booked_slots: {slot_id: slot.id, on_date: date, room_id: room})
                   .pluck("booked_slots.email")
                   .map {|email| {email: email}}

        if_found.empty? ? '-' : if_found[0][:email]
    end

    def if_already_booked(slot, date, room)
        if_booked = Slot.joins(:booked_slot)
                        .where(booked_slots: {slot_id: slot.id, on_date: date, room_id: room})

        if_booked.present? ? true : false 
    end
end

app/views/home_page/landing_page.html.erb
<h1>BOOK YOUR ROOM!!!</h1>


<%= render partial: "room/search_by_date",  locals: {room: @room}%>

<br><br><br>
<div id="show_rooms">
<%= render partial: "room/show_all_rooms", locals: { day: @day, date: @date, room: @room } %>
</div>


<div id="show_room_slots">
<%= render partial: "room/show_room_slots", locals: { day: @day, date: @date, room: @room, slots: @slots, slot: @slot, val: 1 } %>
</div>

<div id ="booking_message">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoomBooking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple-v1.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/room/_form.html.erb
<%= form_for(room, url: room_room_slots_path) do |r| %>
    <span style="display: inline-block;">
      <%= r.label :room, style: "display: inline-block; margin-right: 10px;" %>
      <%= select_tag "room_id", options_for_select(room_names.map { |room| [room[0], room[1]] }) %>
      <%= r.hidden_field :day , :value => day %>
      <%= r.hidden_field :date , :value => date %>
      <%= r.submit 'Check availability', style: "display: inline-block;" %>
    </span>
 <% end %>

app/views/room/_search_by_date.html.erb
<%= form_for(room, url: room_search_room_path) do |r| %>
  <%= r.label :select_a_date %> <br>
  <%= r.date_field :select_a_date, required: true %>
  <%= r.submit 'Choose Date' %>
<% end %>

app/views/room/_show_all_rooms.html.erb
<% if date && day %>
<span> <strong>Date:</strong> <%= date %></span> <br>
<span> <strong>Day:</strong> <%= day %></span> <br><br>

<%= render partial: 'room/form', locals: {day: day, date: date, room: room} %>

<% end %>

app/views/room/_show_room_slots.html.erb
<% if day.present? || date.present? || (room.present? && slots.present?) %>
  <%= form_for(slot, url: room_make_booking_path) do |form| %>
    <table>
      <tr>
        <th>Start Time</th>
        <th>Booked by</th>
        <th>Select</th>
      </tr>
      <% slots.each do |s| %>
        <tr>
          <td><%= s.time %></td>
          <td><%= booked_by_user(s, date, room.id) %></td>
          <td>
            <%= form.hidden_field :day, value: day %>
            <%= form.hidden_field :date, value: date %>
            <%= form.hidden_field :room, value: room.id %>
            <%= form.radio_button :slot_id, s.id , class: "radio_button_hit" , :disabled => if_already_booked(s, date, room.id) %>
          </td>
        </tr>
      <% end %> 
        <tr id = "show_name_field">
            <td colspan="4">
                <%= form.label :name %>
                <%= form.text_field :name, required: true %>
            </td>
        </tr>
        <tr id = "show_email_field">
            <td colspan="4">
                <%= form.label :email %>
                <%= form.text_field :email, required: true %>
            </td>
        </tr>
      <tr>
        <td colspan="4">
          <%= form.submit "Make Booking" %>
        </td>
      </tr>
    </table>
  <% end %>
<% end %>


<script>
$(document).ready(function(){
    $("#show_name_field").hide();
    $("#show_email_field").hide();
    $(".radio_button_hit").change(function(){
        $("#show_name_field").show();
        $("#show_email_field").show();
    })
})
</script>